### ISSUE TITLE
FAIL src/shared/test.ts

### ISSUE THREAD

**Issue by 18810443670** [BOBOlife/mini-vue-core#2]
FAIL src/shared/test.ts
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:175:18)
      at node_modules/@jest/core/build/TestScheduler.js:316:17
      at node_modules/emittery/index.js:260:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:258:23)

**Comment by BOBOlife** [comment]
thank you for your feedback,this issue is solved
